[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x7f7f7f"
blue = "0x5c5cff"
cyan = "0x00ffff"
green = "0x00ff00"
magenta = "0xff00ff"
red = "0xff0000"
white = "0xffffff"
yellow = "0xffff00"

[colors.dim]
black = "0x333333"
blue = "0x6699cc"
cyan = "0x66cccc"
green = "0x99cc99"
magenta = "0xcc99cc"
red = "0xf2777a"
white = "0xdddddd"
yellow = "0xffcc66"

[colors.normal]
black = "0x000000"
blue = "0x0000ee"
cyan = "0x00cdcd"
green = "0x00cd00"
magenta = "0xcc00cd"
red = "0xcd0000"
white = "0xe5e5e5"
yellow = "0xcdcd00"

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[font]
size = 14

[font.normal]
family = "LiterationMono Nerd Font Mono"

[mouse]
hide_when_typing = true

[window]
decorations = "none"
option_as_alt = "Both"
